[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

[[edge_functions]]
  path = "/deepseek-chat"
  function = "deepseek-chat"

[[redirects]]
  from = "/api/extract-text"
  to = "/.netlify/functions/extract-text"
  status = 200

[[redirects]]
  from = "/api/deepseek/chat"
  to = "/deepseek-chat"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/demo"
  to = "/.netlify/functions/auth-demo"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
