[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/deepseek-chat"
  function = "deepseek-chat"

[[redirects]]
  from = "/api/extract-text"
  to = "/.netlify/functions/extract-text"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
