[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Keep SPA routing; we already have public/_redirects but this is a fallback.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
